### ISSUE TITLE
Maven failure when trying to build filters project

### ISSUE THREAD

**Issue by mwunderlich** [matecat/MateCat-Filters#12]
Hi, 

Just wanted to play around with these filters. I am getting the errors listed below when trying to build the filter projec as described in the doc. I am using "mvn clean package". 
Any idea what the problem might be?

[INFO] ------------------------------------------------------------------------
[INFO] Building filters 1.2.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.sf.okapi:okapi-core:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.steps:okapi-step-common:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.steps:okapi-step-whitespace-correction:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.steps:okapi-step-segmentation:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.steps:okapi-step-encodingconversion:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.steps:okapi-step-rainbowkit:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-rainbowkit:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-html:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-plaintext:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-openxml:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-openoffice:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-php:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-its:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-properties:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-po:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-xliff:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-json:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-idml:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-icml:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-txml:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-yaml:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-mif:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-xmlstream:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-table:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-archive:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-xini:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-regex:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-ttx:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-ts:jar:0.30-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for net.sf.okapi.filters:okapi-filter-dtd:jar:0.30-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.379 s
[INFO] Finished at: 2016-09-17T23:30:45+02:00
[INFO] Final Memory: 8M/114M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project filters: Could not resolve dependencies for project com.matecat:filters:jar:1.2.0: The following artifacts could not be resolved: net.sf.okapi:okapi-core:jar:0.30-SNAPSHOT, net.sf.okapi.steps:okapi-step-common:jar:0.30-SNAPSHOT, net.sf.okapi.steps:okapi-step-whitespace-correction:jar:0.30-SNAPSHOT, net.sf.okapi.steps:okapi-step-segmentation:jar:0.30-SNAPSHOT, net.sf.okapi.steps:okapi-step-encodingconversion:jar:0.30-SNAPSHOT, net.sf.okapi.steps:okapi-step-rainbowkit:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-rainbowkit:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-html:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-plaintext:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-openxml:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-openoffice:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-php:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-its:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-properties:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-po:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-xliff:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-json:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-idml:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-icml:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-txml:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-yaml:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-mif:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-xmlstream:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-table:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-archive:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-xini:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-regex:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-ttx:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-ts:jar:0.30-SNAPSHOT, net.sf.okapi.filters:okapi-filter-dtd:jar:0.30-SNAPSHOT: Failure to find net.sf.okapi:okapi-core:jar:0.30-SNAPSHOT in http://repository-okapi.forge.cloudbees.com/release/ was cached in the local repository, resolution will not be reattempted until the update interval of okapi-release has elapsed or updates are forced -> [Help 1]

**Comment by LLCampos** [comment]
There was a bug in that version of Matecat Filters. If you use the most recent one, it should work. ;)

**Comment by mwunderlich** [comment]
Thanks for the reply, Luís. I was building from the master branch. I have now checked dev and tried build the filters there, but I am getting the error. If it's working fine for others, it might something with my local Maven setup.

**Comment by giusilvano** [comment]
Looking at this:

`The following artifacts could not be resolved: net.sf.okapi:okapi-core:jar:0.30-SNAPSHOT`

I suggest you to go in your Okapi folder, checkout on the matecat branch, run `mvn clean install`, and then repeat the `mvn clean package` in your Filters dir.

**Comment by giusilvano** [comment]
@mwunderlich I close the issue for inactivity, but feel free to add details if something else comes up.

**Comment by vuinv** [comment]
@giusilvano I sill met this error with version 1.2.1. Could you help me?

**Comment by giusilvano** [comment]
Hi @vuinv, try following these steps:

1. `git checkout 148296d89a22c91372017c678603b230aa4a4e08` in your local Okapi folder
2. `mvn clean install` in your Okapi folder
3. then try rebuilding MateCat Filters

Hope this works!

**Comment by thomaslauria** [comment]
I get already the following error on 
`mvn clean install`
in the Okapi Folder.

[ERROR] Failed to execute goal on project okapi-filter-rainbowkit: Could not resolve dependencies for project net.sf.okapi.filters:okapi-filter-rainbowkit:jar:0.30-SNAPSHOT: Failure to find net.sf.okapi.lib:okapi-lib-xliff2:jar:1.1.2 in http://maven-eclipse.github.io/maven was cached in the local repository, resolution will not be reattempted until the update interval of maven-eclipse-repo has elapsed or updates are forced -> [Help 1]

**Comment by giusilvano** [comment]
@thomaslauria are you sure you have done `git checkout 148296d89a22c91372017c678603b230aa4a4e08` before?

**Comment by thomaslauria** [comment]
Yes, but I just found the solution: 
The changes of the following commits are missing in the above commit:
https://bitbucket.org/okapiframework/okapi/commits/91452aaed9ff

**Comment by giusilvano** [comment]
Maybe it's a problem with Okapi's tests? Try with `mvn clean install -DskipTests`.

**Comment by thomaslauria** [comment]
No, the problem was the changed repository URL. In the commit 148296d89a22c91372017c678603b230aa4a4e08 the okapi-xliff repositories are still pointing to the old path - which is not working anymore.

**Comment by giusilvano** [comment]
Very strange! The issue never came up on my test platform, even today I was able to reproduce the build process without changing that URL. Maven oddities! If you are ok with this solution I can close the issue.
Anyway, today I just released a new version of the filters referencing a newer Okapi commit. The URL should be already ok there.

**Comment by thomaslauria** [comment]
Yes for me its working, so the solution is ok. Now I am going to test your new release. ;)

**Comment by giusilvano** [comment]
Ok! If something bad comes up feel free to add a new comment or open a new issue.
Thank you! ;)

**Comment by jjmcarrascosa** [comment]
Hi, @giusilvano I confirm the error is still there. Even with the "patch" of @thomaslauria I still get the following error: 

[ERROR] Failed to execute goal on project okapi-filter-rainbowkit: Could not resolve dependencies for project net.sf.okapi.filters:okapi-filter-rainbowkit:jar:0.30-SNAPSHOT: Could not find artifact net.sf.okapi.lib:okapi-lib-xliff2:jar:1.1.2 in maven-eclipse-repo (http://maven-eclipse.github.io/maven) -> [Help 1]

Any help?

**Comment by thomaslauria** [comment]
Hi @jjmcarrascosa, after using M33 instead of M30 there was no error at all. 
That means: download / pull okapi in release M33.
Pull latest matecat filters, there is referenced a new git hash to be pulled. With that it is working.

**Comment by vetrivelc** [comment]
Hi All, I am also facing same issue. Any solutions?

**Comment by giusilvano** [comment]
Hi @vetrivel!
Have you tried following the instructions in the [documentation](https://github.com/matecat/MateCat-Filters/wiki/Build-and-run)? Are you sure you are running the latest code (some weeks ago we released a new version)?
